### ISSUE TITLE
date of birth not show

### ISSUE THREAD

**Issue by santhosh2808** [fssa-batch3/boobalan.ravichandran__web_project#6]
### Description of issue
DOB not getting from any form and not showing

### Expected result
add a input for DOB 

### Steps to reproduce
1. 
2. 
3. 

```
Path:      /pages/user/user_profile.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1347 x 1102 @1.25x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-1--fert-agri-boomi.netlify.app%2Fpages%2Fuser%2Fuser_profile.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1347x1102&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #1](https://deploy-preview-1--fert-agri-boomi.netlify.app/pages/user/user_profile.html)

**Comment by BoobalanRP** [comment]
I have already given that input field in edit profile page. Because DOB birth is not required for all users. So if user want to add DOB then they have to go to profile edit page. Then they can add their DOB to the account.

**Comment by BoobalanRP** [comment]
This issue does not exist here.
